import type { Collection, Product } from "@/types/product";
import type { ShopCategory } from "@/types/shop";

export const CATEGORY_MAP: Record<string, string[]> = {
  Laptops: ["Laptops"],
  Phones: ["Smartphones"],
  Audio: ["Audio"],
  Tablets: ["Tablets"],
  Wearables: ["Wearables"],
  Cameras: ["Cameras", "Photography"],
  Accessories: ["Accessories", "Storage"],
};

export const shopCategories: ShopCategory[] = [
  {
    slug: "laptops",
    label: "Laptops & PCs",
    filterKey: "Laptops",
    productCategories: ["Laptops"],
  },
  {
    slug: "smartphones",
    label: "Smartphones",
    filterKey: "Phones",
    productCategories: ["Smartphones"],
  },
  {
    slug: "audio",
    label: "Audio & Sound",
    filterKey: "Audio",
    productCategories: ["Audio"],
  },
  {
    slug: "tablets",
    label: "Tablets",
    filterKey: "Tablets",
    productCategories: ["Tablets"],
  },
  {
    slug: "wearables",
    label: "Wearables",
    filterKey: "Wearables",
    productCategories: ["Wearables"],
  },
  {
    slug: "cameras",
    label: "Cameras & Photography",
    filterKey: "Cameras",
    productCategories: ["Cameras", "Photography"],
  },
  {
    slug: "accessories",
    label: "Accessories",
    filterKey: "Accessories",
    productCategories: ["Accessories", "Storage"],
  },
];

// Images live in /public/featured_innovation/*.
export const allProducts: Product[] = [
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "Smartphones",
    brand: "Apple",
    price: 1189,
    rating: 4.9,
    reviews: 213,
    image: "/featured_innovation/iphone_15promax.jpeg",
    badge: "SALE",
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    category: "Audio",
    brand: "Sony",
    price: 398,
    rating: 4.8,
    reviews: 176,
    image: "/featured_innovation/Sony_WH.jpeg",
  },
  {
    id: "macbook-pro-16-m3-max",
    name: 'MacBook Pro 16" M3 Max',
    category: "Laptops",
    brand: "Apple",
    price: 2499,
    rating: 5,
    reviews: 98,
    image: "/featured_innovation/MAcBOOK_Air.svg",
  },
  {
    id: "airpods-pro-2",
    name: "AirPods Pro",
    category: "Audio",
    brand: "Apple",
    price: 249,
    rating: 4.7,
    reviews: 142,
    image: "/featured_innovation/AirPod_Pro.svg",
  },
  {
    id: "apple-watch-series-9-2",
    name: "Apple Watch Series 9",
    category: "Wearables",
    brand: "Apple",
    price: 399,
    rating: 4.6,
    reviews: 87,
    image: "/featured_innovation/Apple_Watch.svg",
  },
  {
    id: "canon-eos-r6",
    name: "Canon EOS R6 Mark II",
    category: "Cameras",
    brand: "Canon",
    price: 2499,
    rating: 4.9,
    reviews: 64,
    image: "/featured_innovation/Canon_R6.svg",
  },
];

export const featuredProducts: Product[] = [
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "Smartphones",
    brand: "Apple",
    price: 999,
    rating: 4.9,
    reviews: 320,
    image: "/featured_innovation/iphone_15pro.jpg",
    badge: "BEST SELLER",
  },
  {
    id: "sony-wh-1000xm5-f",
    name: "Sony WH-1000XM5",
    category: "Audio",
    brand: "Sony",
    price: 349.99,
    rating: 4.8,
    reviews: 176,
    image: "/featured_innovation/Sony_WH.jpeg",
  },
  {
    id: "apple-watch-series-9",
    name: "Apple Watch Series 9",
    category: "Wearables",
    brand: "Apple",
    price: 399,
    rating: 4.7,
    reviews: 211,
    image: "/featured_innovation/Apple_Watch.svg",
  },
  {
    id: "canon-eos-r6-f",
    name: "Canon EOS R6 Mark II",
    category: "Cameras",
    brand: "Canon",
    price: 2499,
    rating: 4.9,
    reviews: 64,
    image: "/featured_innovation/Canon_R6.svg",
  },
  {
    id: "elite-gaming-mouse",
    name: "Elite Gaming Mouse",
    category: "Accessories",
    brand: "Logitech",
    price: 129.99,
    rating: 4.6,
    reviews: 143,
    image: "/featured_innovation/elite_gaming_Mouse.png",
  },
  {
    id: "mechanical-pro",
    name: "Mechanical Pro",
    category: "Accessories",
    brand: "Keychron",
    price: 189,
    rating: 4.7,
    reviews: 98,
    image: "/featured_innovation/Mechinical_Pro.svg",
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    category: "Audio",
    brand: "Apple",
    price: 249,
    rating: 4.8,
    reviews: 402,
    image: "/featured_innovation/AirPod_Pro.svg",
  },
  {
    id: "macbook-air-m3",
    name: "MacBook Air M3",
    category: "Laptops",
    brand: "Apple",
    price: 1099,
    rating: 4.9,
    reviews: 187,
    image: "/featured_innovation/MAcBOOK_Air.svg",
  },
];

export const categoryCollections: Collection[] = [
  {
    tag: "HIGH PERFORMANCE",
    title: "Laptops & PCs",
    description: "MacBook Pro, Surface, and Custom Builds.",
    image: "/categories/high_profmnce.svg",
    slug: "laptops",
  },
  {
    tag: "MOBILE LIFE",
    title: "Smartphones",
    description: "iPhone, Galaxy, and Pixel Flagships.",
    image: "/categories/mobile_life.svg",
    slug: "smartphones",
  },
  {
    tag: "IMMERSIVE AUDIO",
    title: "Audio & Sound",
    description: "AirPods, Sony Headphones, and Hi-Fi Speakers.",
    image: "/categories/immersive_audio.svg",
    slug: "audio",
  },
  {
    tag: "VISUAL ARTS",
    title: "Cameras & Photography",
    description: "Canon, Fujifilm, and Professional Lenses.",
    image: "/categories/visual_arts.svg",
    slug: "cameras",
  },
  {
    tag: "SMART LIVING",
    title: "Wearables",
    description: "Apple Watch, Health Trackers, and Smart Rings.",
    image: "/categories/smart_living.svg",
    slug: "wearables",
  },
  {
    tag: "ESSENTIALS",
    title: "Accessories",
    description: "Keyboards, Mice, and Connectivity Hubs.",
    image: "/categories/essential_tools.svg",
    slug: "accessories",
  },
];

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Shop", href: "/shop" },
  { label: "Categories", href: "/categories" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const shopProducts: Product[] = [
  {
    id: "shop-iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "Smartphones",
    brand: "Apple",
    price: 1199,
    rating: 5,
    reviews: 124,
    image: "/featured_innovation/iphone_15promax.jpeg",
  },
  {
    id: "shop-sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    category: "Audio",
    brand: "Sony",
    price: 398,
    rating: 4.5,
    reviews: 340,
    image: "/shop/sony_wh.webp",
  },
  {
    id: "shop-macbook-pro-16",
    name: 'MacBook Pro 16" M3 Max',
    category: "Laptops",
    brand: "Apple",
    price: 2499,
    rating: 5,
    reviews: 89,
    image: "/cart/pro_16.svg",
  },
  {
    id: "shop-ipad-pro-12",
    name: 'iPad Pro 12.9"',
    category: "Tablets",
    brand: "Apple",
    price: 1099,
    rating: 4.5,
    reviews: 210,
    image: "/shop/iPad_pro.webp",
  },
  {
    id: "shop-galaxy-watch-6-pro",
    name: "Galaxy Watch 6 Pro",
    category: "Wearables",
    brand: "Samsung",
    price: 449,
    rating: 4.5,
    reviews: 156,
    image: "/shop/galaxy_8.jpg",
  },
  {
    id: "shop-fujifilm-x100v",
    name: "Fujifilm X100V",
    category: "Photography",
    brand: "Fujifilm",
    price: 1399,
    rating: 5,
    reviews: 921,
    image: "/shop/fujifilm.webp",
  },
  {
    id: "shop-logitech-g-pro-x",
    name: "Logitech G Pro X",
    category: "Accessories",
    brand: "Logitech",
    price: 149,
    rating: 4.5,
    reviews: 408,
    image: "/shop/logitech_gpro.webp",
  },
  {
    id: "shop-samsung-t7-ssd",
    name: "Samsung T7 SSD 2TB",
    category: "Storage",
    brand: "Samsung",
    price: 179,
    rating: 5,
    reviews: 1023,
    image: "/shop/samsung_t7.jpg",
  },
];


/** Single source of truth for shop filtering & category pages */
export const catalogProducts: Product[] = [
  ...shopProducts,
  ...featuredProducts.filter((p) => !shopProducts.some((s) => s.id === p.id)),
];
